workspace(name = "com_google_protobuf_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "protobuf", "protobuf_internal_deps")

protobuf_internal_deps()
protobuf()

new_local_repository(
    name = "submodule_gmock",
    build_file = "@//:third_party/googletest/BUILD.bazel",
    path = "third_party/googletest",
)

bind(
    name = "python_headers",
    actual = "//util/python:python_headers",
)

bind(
    name = "gtest",
    actual = "@submodule_gmock//:gtest",
)

bind(
    name = "gtest_main",
    actual = "@submodule_gmock//:gtest_main",
)