workspace(name = "com_google_protobuf_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "protobuf")
load("//:protobuf_test_deps.bzl", "protobuf_test_deps")	

protobuf_test_deps()
protobuf()

bind(
    name = "six",
    actual = "@six_archive//:six",
)

maven_jar(
        name = "guava_maven",
        artifact = "com.google.guava:guava:18.0",
    )

bind(
    name = "guava",
    actual = "@guava_maven//jar",
)

maven_jar(
        name = "gson_maven",
        artifact = "com.google.code.gson:gson:2.7",
    )

bind(
    name = "gson",
    actual = "@gson_maven//jar",
)

maven_jar(
        name = "error_prone_annotations_maven",
        artifact = "com.google.errorprone:error_prone_annotations:2.3.2",
    )

bind(
    name = "error_prone_annotations",
    actual = "@error_prone_annotations_maven//jar",
)

new_local_repository(
    name = "submodule_gmock",
    build_file = "@com_google_protobuf//:third_party/googletest/BUILD.bazel",
    path = "third_party/googletest",
)

bind(
    name = "python_headers",
    actual = "//util/python:python_headers",
)

bind(
    name = "gtest",
    actual = "@submodule_gmock//:gtest",
)

bind(
    name = "gtest_main",
    actual = "@submodule_gmock//:gtest_main",
)