workspace(name = "com_google_protobuf_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "protobuf")
load("//:test_deps.bzl", "test_deps")

test_deps()
protobuf()

bind(
    name = "six",
    actual = "@six_archive//:six",
)

bind(
    name = "guava",
    actual = "@guava_maven//jar",
)

bind(
    name = "gson",
    actual = "@gson_maven//jar",
)

bind(
    name = "error_prone_annotations",
    actual = "@error_prone_annotations_maven//jar",
)

new_local_repository(
    name = "submodule_gmock",
    build_file = "@//:third_party/googletest/BUILD.bazel",
    path = "third_party/googletest",
)

bind(
    name = "python_headers",
    actual = "//util/python:python_headers",
)

bind(
    name = "gtest",
    actual = "@submodule_gmock//:gtest",
)

bind(
    name = "gtest_main",
    actual = "@submodule_gmock//:gtest_main",
)