workspace(name = "io_bazel_skydoc_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "skydoc")

skydoc(use_deprecated_skydoc=True)

load("//:internal_deps.bzl", "skydoc_internal_deps")	

skydoc_internal_deps()
