workspace(name = "io_bazel_skydoc_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "skydoc")

skydoc(use_deprecated_skydoc=True)

load("//:internal_deps.bzl", "skydoc_internal_deps")	

skydoc_internal_deps()

# TODO(fweikert): Remove everything below this comment once the yarn problem is fixed
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")
node_repositories()

load("@io_bazel_rules_sass//:defs.bzl", "sass_repositories")
sass_repositories()