workspace(name = "bazel_skylib_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("//:deps.bzl", "bazel_skylib_internal_deps")	

bazel_skylib_internal_deps()

load("@bazel_federation//:repositories.bzl", "bazel_skylib")

bazel_skylib()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
