workspace(name = "io_bazel_rules_python_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "rules_python")

rules_python()

load("//:internal_deps.bzl", "rules_python_internal_deps")	

rules_python_internal_deps()

# Node is used by sass. This weird (anti-?)pattern of initializing a repo we
# didn't directly import is taken from Skydoc's WORKSPACE.
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

node_repositories()

load("@io_bazel_rules_sass//:defs.bzl", "sass_repositories")

sass_repositories()

load("@io_bazel_rules_python//python:pip.bzl", "pip_import")

pip_import(
    name = "piptool_deps",
    requirements = "@io_bazel_rules_python//python:requirements.txt",
)

load(
    "@piptool_deps//:requirements.bzl",
    _piptool_install = "pip_install",
)

_piptool_install()

#########################
# Imports for examples. #
#########################

pip_import(
    name = "examples_helloworld",
    requirements = "@io_bazel_rules_python//examples/helloworld:requirements.txt",
)

load(
    "@examples_helloworld//:requirements.bzl",
    _helloworld_install = "pip_install",
)

_helloworld_install()

pip_import(
    name = "examples_version",
    requirements = "@io_bazel_rules_python//examples/version:requirements.txt",
)

load(
    "@examples_version//:requirements.bzl",
    _version_install = "pip_install",
)

_version_install()

pip_import(
    name = "examples_boto",
    requirements = "@io_bazel_rules_python//examples/boto:requirements.txt",
)

load(
    "@examples_boto//:requirements.bzl",
    _boto_install = "pip_install",
)

_boto_install()

pip_import(
    name = "examples_extras",
    requirements = "@io_bazel_rules_python//examples/extras:requirements.txt",
)

load(
    "@examples_extras//:requirements.bzl",
    _extras_install = "pip_install",
)

_extras_install()