workspace(name = "bazel_skylib_federation_example")

local_repository(name = "bazel_federation",
                 path = "..",
)

load("@bazel_federation//:repositories.bzl", "io_bazel_skylib")

io_bazel_skylib()

load("@io_bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# TODO(fweikert): add skydoc to the federation repo and fetch it through the federation
# TODO(fweikert): need a separate mechanism for internal dependencies to avoid cycles
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "io_bazel_skydoc",
    commit = "ac5c106412697ffb9364864070bac796b9bb63d3",  # Feb 27, 2019
    remote = "https://github.com/bazelbuild/skydoc.git",
)

load("@io_bazel_skydoc//skylark:skylark.bzl", "skydoc_repositories")

skydoc_repositories()